services:
  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "15672:15672" # RabbitMQ UI
      - "5672:5672" # AMQP protocol

  mongodb:
    image: "mongo"
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  authentication-service:
    build: ./authentication-service
    container_name: authentication-service
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb+srv://okyeredarkosamuel6:newpassword@cluster0.tcbqe.mongodb.net/authdb?retryWrites=true&w=majority
      - JWT_SECRET=your_jwt_secret_here

  order-service:
    build: ./order-service
    container_name: order-service
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/orderdb
      - RABBITMQ_HOST=rabbitmq

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb+srv://okyeredarkosamuel6:newpassword@cluster0.tcbqe.mongodb.net/productdb?retryWrites=true&w=majority

  notification-service:
    build: ./notification-service
    container_name: notification-service
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq

volumes:
  mongo_data:
